apiVersion: v1
kind: Service
metadata:
  name: docker-nodejs-demo
  namespace: demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: nodejs-port
  selector:
    app: docker-nodejs-demo
  type: NodePort
